export enum PlayerDetailApi {
	activeSw = "active_sw",
	age = "age",
	bats = "bats",
	birthCity = "birth_city",
	birthCountry = "birth_country",
	birthDate = "birth_date",
	birthState = "birth_state",
	college = "college",
	deathCity = "death_city",
	deathCountry = "death_country",
	deathDate = "death_date",
	deathState = "death_state",
	endDate = "end_date",
	fileCode = "file_code",
	gender = "gender",
	heightFeet = "height_feet",
	heightInches = "height_inches",
	highSchool = "high_school",
	jerseyNumber = "jersey_number",
	nameDisplayFirstLast = "name_display_first_last",
	nameDisplayFirstLastHtml = "name_display_first_last_html",
	nameDisplayLastFirst = "name_display_last_first",
	nameDisplayLastFirstHtml = "name_display_last_first_html",
	nameDisplayRoster = "name_display_roster",
	nameDisplayRosterHtml = "name_display_roster_html",
	nameFirst = "name_first",
	nameFull = "name_full",
	nameLast = "name_last",
	nameMatrilineal = "name_matrilineal",
	nameMiddle = "name_middle",
	nameNick = "name_nick",
	namePrefix = "name_prefix",
	nameTitle = "name_title",
	nameUse = "name_use",
	playerId = "player_id",
	primaryPosition = "primary_position",
	primaryPositionTxt = "primary_position_txt",
	primarySportCode = "primary_sport_code",
	primaryStatType = "primary_stat_type",
	proDebutDate = "pro_debut_date",
	startDate = "start_date",
	status = "status",
	statusCode = "status_code",
	statusDate = "status_date",
	teamAbbrev = "team_abbrev",
	teamCode = "team_code",
	teamId = "team_id",
	teamName = "team_name",
	throws = "throws",
	twitterId = "twitter_id",
	weight = "weight"
}

export interface Player {
	activeSw: string,
	age: string,
	bats: string,
	birthCity: string,
	birthCountry: string,
	birthDate: string,
	birthState: string,
	college: string,
	deathCity: string,
	deathCountry: string,
	deathDate: string,
	deathState: string,
	endDate: string,
	fileCode: string,
	gender: string,
	heightFeet: string,
	heightInches: string,
	highSchool: string,
	jerseyNumber: string,
	nameDisplayFirstLast: string,
	nameDisplayFirstLastHtml: string,
	nameDisplayLastFirst: string,
	nameDisplayLastFirstHtml: string,
	nameDisplayRoster: string,
	nameDisplayRosterHtml: string,
	nameFirst: string,
	nameFull: string,
	nameLast: string,
	nameMatrilineal: string,
	nameMiddle: string,
	nameNick: string,
	namePrefix: string,
	nameTitle: string,
	nameUse: string,
	playerId: string,
	primaryPosition: string,
	primaryPositionTxt: string,
	primarySportCode: string,
	primaryStatType: string,
	proDebutDate: string,
	startDate: string,
	status: string,
	statusCode: string,
	statusDate: string,
	teamAbbrev: string,
	teamCode: string,
	teamId: string,
	teamName: string,
	throws: string,
	twitterId: string,
	weight: string
}