export class WebTool {
	public static getMimeType(completeFileName: string): string {
		switch (completeFileName.slice(completeFileName.lastIndexOf('.'))) {
			case '.atom':
				return 'application/atom+xml';
			case '.json':
			case '.map':
			case '.topojson':
				return 'application/json';
			case '.jsonld':
				return 'application/ld+json';
			case '.rss':
				return 'application/rss+xml';
			case '.geojson':
				return 'application/geo+json';
			case '.xml':
				return 'application/xml';
			case '.rdf':
				return 'application/rdf+xml';
			case '.js':
			case '.mjs':
				return 'text/javascript';
			case '.wasm':
				return 'application/wasm';
			case '.webmanifest':
				return 'application/manifest+json';
			case '.webapp':
				return 'application/x-web-app-manifest+json';
			case '.appcache':
				return 'text/cache-manifest';
			case '.mid':
			case '.midi':
			case '.kar':
				return 'audio/midi';
			case '.aac':
			case '.f4a':
			case '.f4b':
			case '.m4a':
				return 'audio/mp4';
			case '.mp3':
				return 'audio/mpeg';
			case '.oga':
			case '.ogg':
			case '.opus':
				return 'audio/ogg';
			case '.ra':
				return 'audio/x-realaudio';
			case '.wav':
				return 'audio/x-wav';
			case '.mka':
				return 'audio/x-matroska';
			case '.bmp':
				return 'image/bmp';
			case '.gif':
				return 'image/gif';
			case '.jpeg':
			case '.jpg':
				return 'image/jpeg';
			case '.jxr':
			case '.hdp':
			case '.wdp':
				return 'image/jxr';
			case '.png':
				return 'image/png';
			case '.svg':
			case '.svgz':
				return 'image/svg+xml';
			case '.tif':
			case '.tiff':
				return 'image/tiff';
			case '.wbmp':
				return 'image/vnd.wap.wbmp';
			case '.webp':
				return 'image/webp';
			case '.jng':
				return 'image/x-jng';
			case '.3gp':
			case '.3gpp':
				return 'video/3gpp';
			case '.f4p':
			case '.f4v':
			case '.m4v':
			case '.mp4':
				return 'video/mp4';
			case '.mpeg':
			case '.mpg':
				return 'video/mpeg';
			case '.ogv':
				return 'video/ogg';
			case '.mov':
				return 'video/quicktime';
			case '.webm':
				return 'video/webm';
			case '.flv':
				return 'video/x-flv';
			case '.mng':
				return 'video/x-mng';
			case '.asf':
			case '.asx':
				return 'video/x-ms-asf';
			case '.wmv':
				return 'video/x-ms-wmv';
			case '.avi':
				return 'video/x-msvideo';
			case '.mkv':
			case '.mk3d':

			case '.woff':
				return 'font/woff';
			case '.woff2':
				return 'font/woff2';
			case '.eot':
				return 'application/vndms-fontobject';
			case '.ttf':
				return 'font/ttf';
			case '.ttc':
				return 'font/collection';
			case '.otf':
				return 'font/otf';
			case '.ear':
			case '.jar':
			case '.war':
				return 'application/java-archive';
			case '.hqx':
				return 'application/mac-binhex40';
			case '.bin':
			case '.deb':
			case '.dll':
			case '.dmg':
			case '.exe':
			case '.img':
			case '.iso':
			case '.msi':
			case '.msm':
			case '.msp':
			case '.safariextz':
				return 'application/octet-stream';
			case '.pdf':
				return 'application/pdf';
			case '.ai':
			case '.eps':
			case '.ps':
				return 'application/postscript';
			case '.rtf':
				return 'application/rtf';
			case '.kml':
				return 'application/vndgoogle-earth.kml+xml';
			case '.kmz':
				return 'application/vndgoogle-earth.kmz';
			case '.wmlc':
				return 'application/vndwap.wmlc';
			case '.7z':
				return 'application/x-7z-compressed';
			case '.bbaw':
				return 'application/x-bb-appworld';
			case '.torrent':
				return 'application/x-bittorrent';
			case '.crx':
				return 'application/x-chrome-extension';
			case '.cco':
				return 'application/x-cocoa';
			case '.jardiff':
				return 'application/x-java-archive-diff';
			case '.jnlp':
				return 'application/x-java-jnlp-file';
			case '.run':
				return 'application/x-makeself';
			case '.oex':
				return 'application/x-opera-extension';
			case '.pl':
			case '.pm':
				return 'application/x-perl';
			case '.pdb':
			case '.prc':
				return 'application/x-pilot';
			case '.rar':
				return 'application/x-rar-compressed';
			case '.rpm':
				return 'application/x-redhat-package-manager';
			case '.sea':
				return 'application/x-sea';
			case '.swf':
				return 'application/x-shockwave-flash';
			case '.sit':
				return 'application/x-stuffit';
			case '.tcl':
			case '.tk':
				return 'application/x-tcl';
			case '.crt':
			case '.der':
			case '.pem':
				return 'application/x-x509-ca-cert';
			case '.xpi':
				return 'application/x-xpinstall';
			case '.xhtml':
				return 'application/xhtml+xml';
			case '.xsl':
				return 'application/xslt+xml';
			case '.zip':
				return 'application/zip';
			case '.ics':
				return 'text/calendar';
			case '.css':
				return 'text/css';
			case '.csv':
				return 'text/csv';
			case '.htm':
			case '.html':
			case '.shtml':
				return 'text/html';
			case '.md':
			case '.markdown':
				return 'text/markdown';
			case '.mml':
				return 'text/mathml';
			case '.txt':
				return 'text/plain';
			case '.vcard':
			case '.vcf':
				return 'text/vcard';
			case '.xloc':
				return 'text/vnd.rim.location.xloc';
			case '.jad':
				return 'text/vnd.sun.j2me.app-descriptor';
			case '.wml':
				return 'text/vnd.wap.wml';
			case '.vtt':
				return 'text/vtt';
			case '.htc':
				return 'text/x-component';
			default:
				return 'text/plain';
		}
	}
}